//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model2classandDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDemo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Salary { get; set; }
        public string Position { get; set; }
        public int DeptDemoId { get; set; }
    
        public virtual DeptDemo DeptDemo { get; set; }
    }
}
