using System;
using System.Collections;
//Q2. Create a class school, having array of student object. Create a class student 
//    having member variable rollnumber, name, marks . rollnumber should be generated by application. 
//    When you load application display school name. Display all student name and marks.

namespace Q02_annonymousObj
{
    class Student {
        static int getRollNo = 0;

        public Student() {
            RollNo = ++getRollNo;
        }
        public Student(string name, int marks) {
            RollNo = ++getRollNo;
            Name = name;
            Marks = marks;
        }
        public int RollNo{ set; get; }
        public string Name { get; set; }
        public int Marks { get; set; }

        public override string ToString()
        {
            return String.Format("{0} {1} {2}", RollNo, Name, Marks);
        }
        
    }
    class School {

        Student[] std = new Student[3];
        public School() {
            std[0] = new Student { Name = "name1", Marks = 60 };
            std[1] = new Student { Name = "name2", Marks = 50 };
            std[2] = new Student { Name = "name3", Marks = 98 };
        }

        public IEnumerator GetEnumerator() {
            return std.GetEnumerator(); 
        }
        
    }
    class Program
    {
        static void Main(string[] args)
        {
            School s1 = new School();

            foreach (Student ss in s1) {
                Console.WriteLine(ss);
            }
        }
    }
}
